### ISSUE TITLE
@qb-logs/client/client.lua:30: bad argument #5 to 'format' (no value)

### ISSUE THREAD

**Issue by b-is-for-brian** [qbcore-framework/qb-logs#1]
Fill all of the webhook spots and still get this.

**Comment by DmACKGL** [comment]
This part of the script it's not in use at the moment, probably was used for a "hetmap" or "livemap" at one time, can be ignored.
https://github.com/qbcore-framework/qb-logs/blob/2357a85b804c0b3653571459ab3b4de0091ac3e0/client/client.lua#L21
